ZERO_IMP_FEATURES = ['LiveCityNotWorkCity',
                     'PrevCancelledToTotalRatio',
                     'FlagOwnRealty',
                     'PrevLastLoanPurpose',
                     'PrevLastLoanInterestRate',
                     'PrevUnusedToTotalRatio',
                     'PrevCodeRejectReasonClientCount',
                     'PrevUnusedofferLoans',
                     'PrevCodeRejectReasonScoCount',
                     'PrevCodeRejectReasonScofrCount',
                     'PrevCodeRejectReasonSystemCount',
                     'PrevCodeRejectReasonVerifCount',
                     'PrevCodeRejectReasonXnaCount',
                     'PrevLastLoanNflagInsuredOnApproval',
                     'CntChildren',
                     'FlagEmail',
                     'PrevContractStatusUnusedofferCount',
                     'PrevLastLoanPaymentType',
                     'CntFamMembers',
                     'PrevHasAnyDpdSum',
                     'PrevContractStatusCanceledCount',
                     'RegRegionNotLiveRegion',
                     'RegRegionNotWorkRegion',
                     'PrevLastLoanProductType',
                     'PrevPortfolioCarsCount',
                     'FlagContMobile',
                     'LiveRegionNotWorkRegion',
                     'FlagEmpPhone',
                     'PrevProductTypeXsellCount',
                     'FlagMobil',
                     'PrevCurrentlyActiveLoans',
                     'PrevCanceledLoans',
                     'PrevLastLoanCodeRejectReason',
                     'RegCityNotLiveCity',
                     'HousetypeMode',
                     'BasementareaAvg',
                     'PrevRateInterestPrimaryStd',
                     'FloorsmaxMedi',
                     'FlagDocument20',
                     'FlagDocument19',
                     'FlagDocument18',
                     'FlagDocument17',
                     'FlagDocument16',
                     'FlagDocument15',
                     'FlagDocument14',
                     'FlagDocument13',
                     'FlagDocument12',
                     'FlagDocument11',
                     'FlagDocument10',
                     'FlagDocument9',
                     'FlagDocument8',
                     'FlagDocument7',
                     'FlagDocument6',
                     'FlagDocument5',
                     'FlagDocument4',
                     'FloorsminMedi',
                     'FlagDocument2',
                     'LivingapartmentsMedi',
                     'NonlivingapartmentsMedi',
                     'EmergencystateMode',
                     'AmtReqCreditBureauHour',
                     'AmtReqCreditBureauDay',
                     'AmtReqCreditBureauWeek',
                     'NonlivingapartmentsAvg',
                     'PrevRateInterestPrimaryMean',
                     'FloorsminAvg',
                     'DefaultRatio',
                     'TotalDefaults',
                     'LivingapartmentsAvg',
                     'FondkapremontMode',
                     'MinbureaucreditDayOverdue',
                     'MinbureaucntCreditProlong',
                     'MinbureauamtCreditSumOverdue',
                     'MinbureauamtCreditSumLimit',
                     'BasementareaMode',
                     'AmtReqCreditBureauMon',
                     'CommonareaMode',
                     'MeanbureaucreditDayOverdue',
                     'MeanbureaucntCreditProlong',
                     'MeanbureauamtCreditSumOverdue',
                     'EntrancesMode',
                     'FloorsmaxMode',
                     'FloorsminMode',
                     'MaxbureaucreditDayOverdue',
                     'MaxbureaucntCreditProlong',
                     'MaxbureauamtCreditSumOverdue',
                     'FlagDocument21']

LOW_IMP_FEATURES = ['NonlivingareaMode',
                    'PrevTotalLoans',
                    'YearsBuildAvg',
                    'BasementareaMedi',
                    'CommonareaMedi',
                    'MinbureauamtAnnuity',
                    'FloorsmaxAvg',
                    'PrevPortfolioXnaCount',
                    'ElevatorsAvg',
                    'PrevPortfolioCashCount',
                    'NameTypeSuite',
                    'PrevRefusedLoans',
                    'LivingapartmentsMode',
                    'ElevatorsMedi',
                    'PrevCodeRejectReasonHcCount',
                    'MinbureauamtCreditSumDebt',
                    'PrevProductTypeXnaCount',
                    'YearsBuildMedi',
                    'NonlivingapartmentsMode']

HIGH_IMP_FEATURES = ['ExtSource2',
 'ExtSource3',
 'ExtSource1',
 'OrganizationType',
 'CodeGender',
 'AmtGoodsPrice',
 'AmtCredit',
 'DaysEmployed',
 'OwnCarAge',
 'NameEducationType',
 'PrevAmtDownPaymentSum',
 'DaysBirth',
 'AmtAnnuity',
 'MeanbureaudaysCredit',
 'MeanbureauamtCreditSumDebt',
 'PrevAvgYieldGroup',
 'NameFamilyStatus',
 'PrevCreditReceivedRequestedDiff',
 'OccupationType',
 'PrevRatioRejectedAccepted',
 'DaysIdPublish',
 'MaxbureaudaysCreditEnddate',
 'PrevLastLoanGoodsCategory',
 'MeanbureauamtCreditMaxOverdue',
 'FlagDocument3']

ANY_IMP_FEATURES = ['ExtSource2',
 'ExtSource3',
 'ExtSource1',
 'OrganizationType',
 'CodeGender',
 'AmtGoodsPrice',
 'AmtCredit',
 'DaysEmployed',
 'OwnCarAge',
 'NameEducationType',
 'PrevAmtDownPaymentSum',
 'DaysBirth',
 'AmtAnnuity',
 'MeanbureaudaysCredit',
 'MeanbureauamtCreditSumDebt',
 'PrevAvgYieldGroup',
 'NameFamilyStatus',
 'PrevCreditReceivedRequestedDiff',
 'OccupationType',
 'PrevRatioRejectedAccepted',
 'DaysIdPublish',
 'MaxbureaudaysCreditEnddate',
 'PrevLastLoanGoodsCategory',
 'MeanbureauamtCreditMaxOverdue',
 'FlagDocument3',
 'MaxbureaudaysCredit',
 'MaxbureaudaysEnddateFact',
 'DaysLastPhoneChange',
 'RegionRatingClientWCity',
 'AmtReqCreditBureauQrt',
 'PrevRatioSumDownPaymentCredit',
 'MeanbureauamtCreditSum',
 'ActiveLoansCount',
 'NameContractType',
 'MaxbureauamtCreditMaxOverdue',
 'WeekdayApprProcessStart',
 'PrevLastLoanDecisionDate',
 'PrevRefusedToTotalRatio',
 'MaxbureauamtCreditSum',
 'MinbureauamtCreditSum',
 'DaysRegistration',
 'PrevHasAnyDpdMean',
 'PrevTotalDpdSum',
 'Def60CntSocialCircle',
 'PrevProductTypeWalkinCount',
 'NameIncomeType',
 'PrevAcceptedToTotalRatio',
 'PrevPortfolioCardsCount',
 'PrevMonthsWithDpdPropMean',
 'AmtIncomeTotal',
 'MeanbureaudaysCreditEnddate',
 'MaxbureauamtCreditSumDebt',
 'Def30CntSocialCircle',
 'PrevLastLoanYieldGroup',
 'RegionPopulationRelative',
 'FlagOwnCar',
 'HourApprProcessStart',
 'LastLoanIssuedDays',
 'PrevAmtCreditSum',
 'PrevContractStatusApprovedCount',
 'MaxbureauamtCreditSumLimit',
 'FlagWorkPhone',
 'MeanbureaudaysCreditUpdate',
 'WallsmaterialMode',
 'YearsBeginexpluatationMode',
 'PrevApprovedLoans']

import pandas as pd
import seaborn as sns


def pandas_config(pd):
    pd.set_option("max_colwidth", 8000)
    pd.options.display.max_rows = 1000
    pd.set_option("display.width", 500)
    pd.set_option("display.max_colwidth", 5000)
    pd.set_option("display.max_colwidth", None)
    pd.set_option("display.width", 2000)

    pd.set_option("display.max_columns", 200)


def plt_config(plt):
    plt.style.use("fivethirtyeight")
    sns.set_theme(style="darkgrid", palette="pastel")
    plt.style.use("fivethirtyeight")
