ZERO_IMP_FEATURES = [
    "TARGET",
    "FlagOwnCar",
    "FlagOwnRealty",
    "CntChildren",
    "NameTypeSuite",
    "FlagMobil",
    "FlagEmpPhone",
    "FlagContMobile",
    "FlagEmail",
    "CntFamMembers",
    "RegionRatingClient",
    "RegRegionNotLiveRegion",
    "RegRegionNotWorkRegion",
    "LiveRegionNotWorkRegion",
    "RegCityNotLiveCity",
    "RegCityNotWorkCity",
    "LiveCityNotWorkCity",
    "BasementareaAvg",
    "YearsBeginexpluatationAvg",
    "YearsBuildAvg",
    "ElevatorsAvg",
    "FloorsmaxAvg",
    "FloorsminAvg",
    "LivingapartmentsAvg",
    "NonlivingapartmentsAvg",
    "NonlivingareaAvg",
    "BasementareaMode",
    "CommonareaMode",
    "ElevatorsMode",
    "EntrancesMode",
    "FloorsmaxMode",
    "FloorsminMode",
    "LivingapartmentsMode",
    "LivingareaMode",
    "NonlivingapartmentsMode",
    "NonlivingareaMode",
    "BasementareaMedi",
    "YearsBuildMedi",
    "CommonareaMedi",
    "ElevatorsMedi",
    "FloorsmaxMedi",
    "FloorsminMedi",
    "LandareaMedi",
    "LivingapartmentsMedi",
    "NonlivingapartmentsMedi",
    "FondkapremontMode",
    "HousetypeMode",
    "EmergencystateMode",
    "FlagDocument2",
    "FlagDocument4",
    "FlagDocument5",
    "FlagDocument6",
    "FlagDocument7",
    "FlagDocument8",
    "FlagDocument9",
    "FlagDocument10",
    "FlagDocument11",
    "FlagDocument12",
    "FlagDocument13",
    "FlagDocument14",
    "FlagDocument15",
    "FlagDocument16",
    "FlagDocument17",
    "FlagDocument18",
    "FlagDocument19",
    "FlagDocument20",
    "FlagDocument21",
    "AmtReqCreditBureauHour",
    "AmtReqCreditBureauDay",
    "AmtReqCreditBureauWeek",
    "AmtReqCreditBureauMon",
    "MaxbureauamtCreditSumOverdue",
    "MaxbureaucntCreditProlong",
    "MaxbureaucreditDayOverdue",
    "MeanbureauamtCreditSumOverdue",
    "MeanbureaucntCreditProlong",
    "MeanbureaucreditDayOverdue",
    "MinbureauamtAnnuity",
    "MinbureauamtCreditSumDebt",
    "MinbureauamtCreditSumLimit",
    "MinbureauamtCreditSumOverdue",
    "MinbureaucntCreditProlong",
    "MinbureaucreditDayOverdue",
    "TotalDefaults",
    "DefaultRatio",
    "LastLoanIssuedDays",
    "PrevRateInterestPrimaryMean",
    "PrevRateInterestPrimaryStd",
    "PrevHasAnyDpdSum",
    "PrevLastLoanInterestRate",
    "PrevLastLoanPurpose",
    "PrevLastLoanPaymentType",
    "PrevLastLoanCodeRejectReason",
    "PrevLastLoanPortfolio",
    "PrevLastLoanProductType",
    "PrevContractStatusCanceledCount",
    "PrevContractStatusRefusedCount",
    "PrevContractStatusUnusedofferCount",
    "PrevPortfolioCarsCount",
    "PrevPortfolioCashCount",
    "PrevPortfolioXnaCount",
    "PrevProductTypeXnaCount",
    "PrevProductTypeXsellCount",
    "PrevCurrentlyActiveLoans",
    "PrevApprovedLoans",
    "PrevCanceledLoans",
    "PrevRefusedLoans",
    "PrevUnusedofferLoans",
    "PrevTotalLoans",
    "PrevCancelledToTotalRatio",
    "PrevUnusedToTotalRatio",
    "PrevCodeRejectReasonClientCount",
    "PrevCodeRejectReasonHcCount",
    "PrevCodeRejectReasonScoCount",
    "PrevCodeRejectReasonScofrCount",
    "PrevCodeRejectReasonSystemCount",
    "PrevCodeRejectReasonVerifCount",
    "PrevCodeRejectReasonXnaCount",
    "PrevLastLoanNflagInsuredOnApproval",
]

LOW_IMP_FEATURES = [
    "NonlivingareaMode",
    "PrevTotalLoans",
    "YearsBuildAvg",
    "BasementareaMedi",
    "CommonareaMedi",
    "MinbureauamtAnnuity",
    "FloorsmaxAvg",
    "PrevPortfolioXnaCount",
    "ElevatorsAvg",
    "PrevPortfolioCashCount",
    "NameTypeSuite",
    "PrevRefusedLoans",
    "LivingapartmentsMode",
    "ElevatorsMedi",
    "PrevCodeRejectReasonHcCount",
    "MinbureauamtCreditSumDebt",
    "PrevProductTypeXnaCount",
    "YearsBuildMedi",
    "NonlivingapartmentsMode",
]

HIGH_IMP_FEATURES = [
    "ExtSource2",
    "ExtSource3",
    "AmtCredit",
    "AmtGoodsPrice",
    "ExtSource1",
    "CodeGender",
    "OwnCarAge",
    "DaysEmployed",
    "OrganizationType",
    "DaysBirth",
    "NameEducationType",
    "MeanbureauamtCreditSumDebt",
    "AmtAnnuity",
    "PrevAvgYieldGroup",
    "DaysIdPublish",
    "PrevCreditReceivedRequestedDiff",
    "NameFamilyStatus",
    "PrevAmtDownPaymentSum",
    "MaxbureaudaysCredit",
    "MaxbureaudaysCreditEnddate",
    "FlagDocument3",
    "OccupationType",
    "MaxbureaudaysEnddateFact",
    "MeanbureauamtCreditSum",
]

ANY_IMP_FEATURES = [
    "ExtSource2",
    "ExtSource3",
    "AmtCredit",
    "AmtGoodsPrice",
    "ExtSource1",
    "CodeGender",
    "OwnCarAge",
    "DaysEmployed",
    "OrganizationType",
    "DaysBirth",
    "NameEducationType",
    "MeanbureauamtCreditSumDebt",
    "AmtAnnuity",
    "PrevAvgYieldGroup",
    "DaysIdPublish",
    "PrevCreditReceivedRequestedDiff",
    "NameFamilyStatus",
    "PrevAmtDownPaymentSum",
    "MaxbureaudaysCredit",
    "MaxbureaudaysCreditEnddate",
    "FlagDocument3",
    "OccupationType",
    "MaxbureaudaysEnddateFact",
    "MeanbureauamtCreditSum",
    "RegionRatingClientWCity",
    "PrevLastLoanGoodsCategory",
    "PrevLastLoanDecisionDate",
    "PrevPortfolioCardsCount",
    "DaysLastPhoneChange",
    "PrevRatioSumDownPaymentCredit",
    "AmtReqCreditBureauQrt",
    "MinbureauamtCreditSum",
    "MeanbureauamtCreditMaxOverdue",
    "PrevHasAnyDpdMean",
    "MeanbureaudaysCredit",
    "WeekdayApprProcessStart",
    "MaxbureauamtCreditSum",
    "FlagWorkPhone",
    "MaxbureauamtCreditMaxOverdue",
    "PrevContractStatusApprovedCount",
    "NameIncomeType",
    "PrevRatioRejectedAccepted",
    "ActiveLoansCount",
    "RegionPopulationRelative",
    "PrevAcceptedToTotalRatio",
    "Def30CntSocialCircle",
    "PrevLastLoanYieldGroup",
    "PrevLastLoanClientType",
    "PrevPortfolioPosCount",
    "AmtIncomeTotal",
    "PrevAmtApplicationSum",
    "NameContractType",
    "PrevTotalDpdSum",
    "MaxbureaudaysCreditUpdate",
    "MeanbureaudaysCreditEnddate",
    "MaxbureauamtCreditSumLimit",
    "MeanbureauskIdBureau",
    "MeanbureaudaysCreditUpdate",
    "MinbureaudaysCreditUpdate",
    "DaysRegistration",
    "MinbureauskIdBureau",
    "HourApprProcessStart",
    "WallsmaterialMode",
    "PrevRefusedToTotalRatio",
    "FlagPhone",
    "PrevLastLoanContractStatus",
    "PrevAmtApplicationMean",
    "PrevAmtCreditSum",
    "Def60CntSocialCircle",
    "AmtReqCreditBureauYear",
    "MeanbureauamtCreditSumLimit",
    "EntrancesMedi",
    "PrevAvgNflagInsuredOnApproval",
    "PrevDaysAfterFirstApplication",
    "YearsBeginexpluatationMode",
    "NameHousingType",
    "PrevAmtCreditMean",
    "PrevProductTypeWalkinCount",
    "PrevCodeRejectReasonLimitCount",
    "Countbureau",
    "PrevMonthsWithDpdPropMean",
    "MaxbureauamtCreditSumDebt",
    "MaxbureauskIdBureau",
    "MinbureaudaysCreditEnddate",
    "YearsBeginexpluatationMedi",
    "PrevTotalPreviousLoans",
    "ApartmentsMode",
    "MinbureaudaysEnddateFact",
    "ApartmentsAvg",
    "TotalareaMode",
    "MinbureaudaysCredit",
    "LandareaMode",
    "EntrancesAvg",
    "Obs60CntSocialCircle",
    "MeanbureauamtAnnuity",
    "MeanbureaudaysEnddateFact",
    "NonlivingareaMedi",
    "ApartmentsMedi",
    "CommonareaAvg",
    "MaxbureauamtAnnuity",
    "MinbureauamtCreditMaxOverdue",
    "PrevCodeRejectReasonXapCount",
    "Obs30CntSocialCircle",
    "LandareaAvg",
    "YearsBuildMode",
    "PrevMonthsWithDpdPropSum",
    "LivingareaMedi",
    "LivingareaAvg",
]

import pandas as pd
import seaborn as sns


def pandas_config(pd):
    pd.set_option("max_colwidth", 8000)
    pd.options.display.max_rows = 1000
    pd.set_option("display.width", 500)
    pd.set_option("display.max_colwidth", 5000)
    pd.set_option("display.max_colwidth", None)
    pd.set_option("display.width", 2000)

    pd.set_option("display.max_columns", 200)


def plt_config(plt):
    plt.style.use("fivethirtyeight")
    sns.set_theme(style="darkgrid", palette="pastel")
    plt.style.use("fivethirtyeight")


def calculate_metrics(group):
    default_rate = group["target__loan_status"].mean()
    mean_interest_rate = group["pass__int_rate"].mean()
    expected_return = (1 - default_rate) * mean_interest_rate
    return pd.Series(
        {
            "default_rate": default_rate,
            "mean_interest_rate": mean_interest_rate,
            "expected_return": expected_return,
        }
    )
